// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYGgSezj3LLSK-wZUqTM2iwYdGIB55UQ',
    appId: '1:1018953680694:web:f43725eed8c6a3b88c1597',
    messagingSenderId: '1018953680694',
    projectId: 'i-closet-nuray',
    authDomain: 'i-closet-nuray.firebaseapp.com',
    storageBucket: 'i-closet-nuray.firebasestorage.app',
    measurementId: 'G-Y0H9J0VKQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XQh996eFinl8QURUqj562aahAwbfTf4',
    appId: '1:1018953680694:android:d093d63d6bfe5d468c1597',
    messagingSenderId: '1018953680694',
    projectId: 'i-closet-nuray',
    storageBucket: 'i-closet-nuray.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_O3vBSaw3fG5xaFp8E7ZJpVfa3Rf-NE',
    appId: '1:1018953680694:ios:d57c58ef3c2db4ba8c1597',
    messagingSenderId: '1018953680694',
    projectId: 'i-closet-nuray',
    storageBucket: 'i-closet-nuray.firebasestorage.app',
    androidClientId: '1018953680694-odb9fdvgh7cbmefvfb91ul1gnq1hd0pk.apps.googleusercontent.com',
    iosClientId: '1018953680694-1tbkhq8hjssp8t65othgumnoponpl4oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualWardrobeAi',
  );
}
